import Link from "next/link";
import { PageShell } from "@/components/page-shell";
import { metadataExample, submissionInstructions } from "@/lib/submission-instructions";

export default function SubmitPage() {
  return (
    <PageShell
      eyebrow="Submission"
      title="Submit a manuscript"
      description="Upload your manuscript packet to SciLayer. SciLayer archives your files to GitHub after upload—you do not commit to GitHub yourself."
    >
      <div className="grid gap-6 lg:grid-cols-[1fr_0.9fr]">
        <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-xl font-black text-slate-950">How submission works</h2>
          <pre className="mt-4 rounded-2xl bg-slate-950 p-5 text-sm leading-6 text-slate-50 whitespace-pre-wrap">
            {submissionInstructions}
          </pre>
          <Link
            href="/submissions/upload"
            className="mt-6 inline-flex rounded-full bg-cyan-600 px-5 py-3 text-sm font-bold text-white hover:bg-cyan-700"
          >
            Upload manuscript packet
          </Link>
        </section>
        <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-xl font-black text-slate-950">metadata.yml (generated by SciLayer)</h2>
          <p className="mt-2 text-sm text-slate-600">
            After upload, SciLayer writes metadata to the SciLayer GitHub archive automatically.
          </p>
          <pre className="mt-4 rounded-2xl bg-slate-100 p-5 text-xs leading-5 text-slate-800">
            {metadataExample}
          </pre>
        </section>
      </div>
    </PageShell>
  );
}
